### ISSUE TITLE
can't compile under openwrt sdk or source

### ISSUE THREAD

**Issue by helllkz** [yhfudev/openwrt-fcgiwrap#1]
I always get this error message and I don't know how to fix it.

fcgiwrap.c: In function 'handle_fcgi_request':
fcgiwrap.c:581:4: error: this statement may fall through [-Werror=implicit-fallthrough=]
    cgi_error("502 Bad Gateway", "Cannot execute script", filename);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fcgiwrap.c:583:3: note: here
   default: /* parent */
   ^~~~~~~
cc1: all warnings being treated as errors
<builtin>: recipe for target 'fcgiwrap' failed
make[3]: *** [fcgiwrap] Error 1
make[3]: Leaving directory '/home/ubuntu/openwrt/sdk/build_dir/target-x86_64_musl/fcgiwrap-1.1.0'
Makefile:61: recipe for target '/home/ubuntu/openwrt/sdk/build_dir/target-x86_64_musl/fcgiwrap-1.1.0/.built' failed
make[2]: *** [/home/ubuntu/openwrt/sdk/build_dir/target-x86_64_musl/fcgiwrap-1.1.0/.built] Error 2
make[2]: Leaving directory '/home/ubuntu/openwrt/sdk/package/openwrt-fcgiwrap'
Command exited with non-zero status 2
time: package/openwrt-fcgiwrap/compile#2.21#0.54#3.79
package/Makefile:107: recipe for target 'package/openwrt-fcgiwrap/compile' failed
make[1]: *** [package/openwrt-fcgiwrap/compile] Error 2
make[1]: Leaving directory '/home/ubuntu/openwrt/sdk'
/home/ubuntu/openwrt/sdk/include/toplevel.mk:209: recipe for target 'package/openwrt-fcgiwrap/compile' failed
make: *** [package/openwrt-fcgiwrap/compile] Error 2

**Comment by helllkz** [comment]
Fixed this issue, but there is another issue

WARNING: Makefile 'package/linux/Makefile' has a dependency on 'kmod-phy-bcm-ns-usb2', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'kmod-phy-bcm-ns-usb3', which does not exist
bash: gtime: command not found
make[3]: *** [package/feeds/packages/perl/prereq] Error 127
make[2]: *** [/home/admin/sdk/staging_dir/target-x86_64_musl/stamp/.package_prereq] Error 2

**Comment by yhfudev** [comment]
It's the problem from the "package/feeds/packages/perl/prereq", you may check the line "bash: gtime: command not found" which caused the error.

**Comment by kofec** [comment]
@helllkz 
How you fix it ?:
```
make[3]: Entering directory '/mnt/openwrt/OpenwrtRaspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/fcgiwrap-1.1.0'
arm-openwrt-linux-muslgnueabi-gcc -std=gnu99 -Wall -Wextra -Werror -pedantic -Os -pipe -mcpu=arm1176jzf-s -mfpu=vfp -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -iremap/mnt/openwrt/OpenwrtRaspberry/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/fcgiwrap-1.1.0:fcgiwrap-1.1.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro    -L/mnt/openwrt/OpenwrtRaspberry/staging_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/usr/lib -L/mnt/openwrt/OpenwrtRaspberry/staging_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/lib -L/mnt/openwrt/OpenwrtRaspberry/staging_dir/toolchain-arm_arm1176jzf-s+vfp_gcc-7.3.0_musl_eabi/usr/lib -L/mnt/openwrt/OpenwrtRaspberry/staging_dir/toolchain-arm_arm1176jzf-s+vfp_gcc-7.3.0_musl_eabi/lib -znow -zrelro    fcgiwrap.c  -lfcgi  -o fcgiwrap
fcgiwrap.c: In function 'handle_fcgi_request':
fcgiwrap.c:581:4: error: this statement may fall through [-Werror=implicit-fallthrough=]
    cgi_error("502 Bad Gateway", "Cannot execute script", filename);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fcgiwrap.c:583:3: note: here
   default: /* parent */
   ^~~~~~~
cc1: all warnings being treated as errors
<builtin>: recipe for target 'fcgiwrap' failed
make[3]: *** [fcgiwrap] Error 1

```

**Comment by abiuan** [comment]
Hello,
I'trying to compile fcgiwrap with onion 18.06 SDK. I still have the same error:
`fcgiwrap.c:581:4: error: this statement may fall through [-Werror=implicit-fallthrough=]
    cgi_error("502 Bad Gateway", "Cannot execute script", filename);`

Do you know how to fix it?

Best regards
